const { Command } = require("discord.js-commando");

module.exports = class KissCommand extends Command {
  constructor(client) {
    super(client, {
      name: "rose",
      memberName: "rose",
      group: "fun",
      description: "Give a member a rose",
      guildOnly: true,
    });
  }

  /**
   * @param {import("discord.js").Message} message
   * @return {*}
   */
  run(message) {
    const member = message.mentions.members.first();
    if (member) {
      if (member.id === this.client.user.id) {
        return message.channel.send("`holdobject.js` not found");
      } else if (member.id === message.author.id) {
        return message.channel.send("You can't give yourself a rose.");
      } else {
        const roses = [
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `🌷`,
          `🌹`,
          `🌺`,
          `🌻`,
          `🌸`,
          `💎`,
        ];
        const rose = roses[Math.floor(Math.random() * roses.length)];
        return message.channel.send(
          `Hey ${member.user}, ${message.author} just gave you a great big kiss! 😘`
        );
      }
    } else {
      return message.channel.send(
        `${member.user}, ${message.member} has decided to give you a rose! ${rose}`
      );
    }
  }
};
